application: bulbware
version: 3-1-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js
#  expiration: "7d"

- url: /public
  static_dir: public
#  expiration: "7d"

- url: /api/.*
  script: bulbware_api.app
  login: required

- url: /user/.*
  script: user_api.app
  login: required

- url: /dashboard/.*
  script: dashboard.app
  login: required

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
